import 'server-only';

import { customProvider, extractReasoningMiddleware, wrapLanguageModel } from 'ai';
import { createOpenAICompatible } from '@ai-sdk/openai-compatible';

const reasoningMiddleware = extractReasoningMiddleware({
  tagName: 'think',
});

const openrouterReferer = (process.env.ALLOWED_ORIGINS?.split(',')[0] ?? 'https://mydatavibes.com').trim();

const openrouter = createOpenAICompatible({
  name: 'openrouter',
  baseURL: 'https://openrouter.ai/api/v1',
  apiKey: process.env.OPENROUTER_API_KEY,
  headers: {
    'HTTP-Referer': openrouterReferer,
    'X-Title': 'Datavibes AI',
  },
});

const OPENROUTER_MODEL_IDS = {
  'scira-arch-router': 'katanemo/arch-router-1.5b',
  'scira-auto': 'x-ai/grok-4.3',
  'scira-default': 'x-ai/grok-4.3',
  'scira-ext-1': 'x-ai/grok-4.3',
  'scira-ext-2': 'openai/gpt-5.4',
  'scira-ext-3': 'anthropic/claude-sonnet-4.6',
  'scira-ext-4': 'z-ai/glm-4.7-flash',
  'scira-ext-5': 'moonshotai/kimi-k2.5',
  'scira-ext-6': 'google/gemini-3.1-pro-preview',
  'scira-ext-7': 'qwen/qwen3.5-flash',
  'scira-ext-8': 'x-ai/grok-4.20',
  'scira-name': 'google/gemini-2.5-flash-lite',
  'scira-follow-up': 'google/gemini-2.5-flash-lite',
  'scira-nano': 'meta-llama/llama-3.3-70b-instruct',
  'scira-llama-guard': 'meta-llama/llama-guard-4-12b',
  'scira-enhance': 'moonshotai/kimi-k2-0905',
  'scira-code': 'x-ai/grok-code-fast-1',
  'scira-grok-3': 'x-ai/grok-3',
  'scira-grok-3-mini': 'x-ai/grok-3-mini',
  'scira-grok-4': 'x-ai/grok-4',
  'scira-grok-4.20-experimental-beta-0304': 'x-ai/grok-4.20',
  'scira-grok-4.20-experimental-beta-0304-thinking': 'x-ai/grok-4.20',
  'scira-grok-4-fast': 'x-ai/grok-4-fast',
  'scira-grok-4-fast-think': 'x-ai/grok-4-fast',
  'scira-grok-4.3-thinking': 'x-ai/grok-4.3',
  'scira-grok4.1-fast-thinking': 'x-ai/grok-4.1-fast',
  'scira-gpt-4.1': 'openai/gpt-4.1',
  'scira-gpt-4.1-mini': 'openai/gpt-4.1-mini',
  'scira-gpt-4.1-nano': 'openai/gpt-4.1-nano',
  'scira-gpt-5.1': 'openai/gpt-5.1',
  'scira-gpt-5.1-thinking': 'openai/gpt-5.1',
  'scira-gpt-5.1-codex': 'openai/gpt-5.1-codex',
  'scira-gpt-5.1-codex-max': 'openai/gpt-5.1-codex-max',
  'scira-gpt-5.1-codex-mini': 'openai/gpt-5.1-codex-mini',
  'scira-gpt-5.2': 'openai/gpt-5.2',
  'scira-gpt-5.2-codex': 'openai/gpt-5.2-codex',
  'scira-gpt-5.2-thinking': 'openai/gpt-5.2',
  'scira-gpt-5.2-thinking-xhigh': 'openai/gpt-5.2',
  'scira-gpt-5.3-chat-latest': 'openai/gpt-5.3-chat-latest',
  'scira-gpt-5.3-codex': 'openai/gpt-5.3-codex',
  'scira-gpt-5.4': 'openai/gpt-5.4',
  'scira-gpt-5.4-mini': 'openai/gpt-5.4-mini',
  'scira-gpt-5.4-nano': 'openai/gpt-5.4-nano',
  'scira-gpt-5.4-thinking': 'openai/gpt-5.4',
  'scira-gpt-5.4-thinking-xhigh': 'openai/gpt-5.4',
  'scira-gpt5': 'openai/gpt-5',
  'scira-gpt5-codex': 'openai/gpt-5-codex',
  'scira-gpt5-medium': 'openai/gpt-5',
  'scira-gpt5-mini': 'openai/gpt-5-mini',
  'scira-gpt5-nano': 'openai/gpt-5-nano',
  'scira-gpt-oss-20': 'openai/gpt-oss-20b',
  'scira-gpt-oss-120': 'openai/gpt-oss-120b',
  'scira-o3': 'openai/o3',
  'scira-o4-mini': 'openai/o4-mini',
  'scira-anthropic-small': 'anthropic/claude-haiku-4.5',
  'scira-anthropic': 'anthropic/claude-sonnet-4.5',
  'scira-anthropic-think': 'anthropic/claude-sonnet-4.5',
  'scira-anthropic-sonnet-4.6': 'anthropic/claude-sonnet-4.6',
  'scira-anthropic-sonnet-4.6-think': 'anthropic/claude-sonnet-4.6',
  'scira-anthropic-opus': 'anthropic/claude-opus-4.5',
  'scira-anthropic-opus-think': 'anthropic/claude-opus-4.5',
  'scira-anthropic-opus-4.6': 'anthropic/claude-opus-4.6',
  'scira-anthropic-opus-4.6-think': 'anthropic/claude-opus-4.6',
  'scira-google-lite': 'google/gemini-2.5-flash-lite',
  'scira-google': 'google/gemini-2.5-flash',
  'scira-google-think': 'google/gemini-2.5-flash',
  'scira-google-pro': 'google/gemini-2.5-pro',
  'scira-google-pro-think': 'google/gemini-2.5-pro',
  'scira-gemini-3-flash': 'google/gemini-3-flash-preview',
  'scira-gemini-3-flash-think': 'google/gemini-3-flash-preview',
  'scira-gemini-3.1-flash-lite': 'google/gemini-3.1-flash-lite-preview',
  'scira-gemini-3.1-flash-lite-think': 'google/gemini-3.1-flash-lite-preview',
  'scira-gemini-3.1-pro': 'google/gemini-3.1-pro-preview',
  'scira-qwen-4b': 'qwen/qwen3-4b:free',
  'scira-qwen-4b-thinking': 'qwen/qwen3-4b:free',
  'scira-qwen-32b': 'qwen/qwen3-32b',
  'scira-qwen-32b-thinking': 'qwen/qwen3-32b',
  'scira-qwen-30': 'qwen/qwen3-30b-a3b-instruct-2507',
  'scira-qwen-30-think': 'qwen/qwen3-30b-a3b-thinking-2507',
  'scira-qwen-235': 'qwen/qwen3-235b-a22b',
  'scira-qwen-235-think': 'qwen/qwen3-235b-a22b-thinking-2507',
  'scira-qwen-coder-small': 'qwen/qwen3-coder-30b-a3b-instruct',
  'scira-qwen-coder': 'qwen/qwen3-coder',
  'scira-qwen-coder-plus': 'qwen/qwen3-coder-plus',
  'scira-qwen-coder-next': 'qwen/qwen3-coder-next',
  'scira-qwen-3-vl': 'qwen/qwen3-vl-235b-a22b-instruct',
  'scira-qwen-3-vl-thinking': 'qwen/qwen3-vl-235b-a22b-thinking',
  'scira-qwen-3-vl-30b': 'qwen/qwen3-vl-30b-a3b-instruct',
  'scira-qwen-3-vl-30b-thinking': 'qwen/qwen3-vl-30b-a3b-thinking',
  'scira-qwen-3-next': 'qwen/qwen3-next-80b-a3b-instruct',
  'scira-qwen-3-next-think': 'qwen/qwen3-next-80b-a3b-thinking',
  'scira-qwen-3-max': 'qwen/qwen3-max',
  'scira-qwen-3-max-preview': 'qwen/qwen3-max',
  'scira-qwen-3-max-preview-thinking': 'qwen/qwen3-max-thinking',
  'scira-qwen-3.5-27b': 'qwen/qwen3.5-27b',
  'scira-qwen-3.5-35b': 'qwen/qwen3.5-35b-a3b',
  'scira-qwen-3.5-122b': 'qwen/qwen3.5-122b-a10b',
  'scira-qwen-3.5': 'qwen/qwen3.5-397b-a17b',
  'scira-qwen-3.5-plus': 'qwen/qwen3.5-plus',
  'scira-qwen-3.5-flash': 'qwen/qwen3.5-flash',
  'scira-deepseek-v3': 'deepseek/deepseek-chat-v3-0324',
  'scira-deepseek-v3.1-terminus': 'deepseek/deepseek-v3.1-terminus',
  'scira-deepseek-chat': 'deepseek/deepseek-v3.2',
  'scira-deepseek-chat-think': 'deepseek/deepseek-v3.2',
  'scira-deepseek-chat-exp': 'deepseek/deepseek-v3.2-exp',
  'scira-deepseek-chat-think-exp': 'deepseek/deepseek-v3.2-exp',
  'scira-deepseek-r1': 'deepseek/deepseek-r1',
  'scira-deepseek-r1-0528': 'deepseek/deepseek-r1-0528',
  'scira-glm-air': 'z-ai/glm-4.5-air',
  'scira-glm': 'z-ai/glm-4.5',
  'scira-glm-4.6': 'z-ai/glm-4.6',
  'scira-glm-4.6v-flash': 'z-ai/glm-4.7-flash',
  'scira-glm-4.6v': 'z-ai/glm-4.6v',
  'scira-glm-4.7': 'z-ai/glm-4.7',
  'scira-glm-4.7-flash': 'z-ai/glm-4.7-flash',
  'scira-glm-5': 'z-ai/glm-5',
  'scira-glm-5-thinking': 'z-ai/glm-5',
  'scira-kimi-k2-v2': 'moonshotai/kimi-k2-0905',
  'scira-kimi-k2-v2-thinking': 'moonshotai/kimi-k2-thinking',
  'scira-kimi-k2.5': 'moonshotai/kimi-k2.5',
  'scira-kimi-k2.5-thinking': 'moonshotai/kimi-k2.5',
  'scira-mistral-large': 'mistralai/mistral-large-2512',
  'scira-mistral-medium': 'mistralai/mistral-medium-3.1',
  'scira-mistral-small': 'mistralai/mistral-small-3.2-24b-instruct',
  'scira-mistral-small-think': 'mistralai/mistral-small-3.2-24b-instruct',
  'scira-ministral-3b': 'mistralai/ministral-3b-2512',
  'scira-ministral-8b': 'mistralai/ministral-8b-2512',
  'scira-ministral-14b': 'mistralai/ministral-14b-2512',
  'scira-magistral-small': 'mistralai/magistral-small-2509',
  'scira-magistral-medium': 'mistralai/magistral-medium-2509',
  'scira-leanstral': 'mistralai/leanstral',
  'scira-devstral': 'mistralai/devstral-2512',
  'scira-devstral-small': 'mistralai/devstral-small',
  'scira-minimax': 'minimax/minimax-m1',
  'scira-minimax-m2': 'minimax/minimax-m2',
  'scira-minimax-m2.1': 'minimax/minimax-m2.1',
  'scira-minimax-m2.1-lightning': 'minimax/minimax-m2.1-lightning',
  'scira-minimax-m2.5': 'minimax/minimax-m2.5',
  'scira-minimax-m2.7': 'minimax/minimax-m2.7',
  'scira-cmd-a': 'cohere/command-a',
  'scira-cmd-a-think': 'cohere/command-a',
  'scira-trinity-mini': 'arcee-ai/trinity-mini',
  'scira-trinity-large': 'arcee-ai/trinity-large-preview:free',
  'scira-step-3.5-flash': 'stepfun/step-3.5-flash:free',
  'scira-kat-coder': 'kwaipilot/kat-coder-pro',
  'scira-mimo-v2-flash': 'xiaomi/mimo-v2-flash',
  'scira-mimo-v2-pro': 'xiaomi/mimo-v2-pro',
  'scira-nova-2-lite': 'amazon/nova-2-lite-v1',
  'scira-nemotron-3-super': 'nvidia/nemotron-3-120b-a12b',
  'scira-v0-10': 'openai/gpt-5.1-codex-mini',
  'scira-v0-15': 'openai/gpt-5.1-codex',
  'scira-sarvam-105b': 'sarvamai/sarvam-105b',
  'scira-seed-1.6': 'bytedance/seed-1.6',
  'scira-seed-1.6-flash': 'bytedance/seed-1.6-flash',
  'scira-seed-1.8': 'bytedance/seed-1.8',
  'scira-seed-2.0-mini': 'bytedance/seed-2.0-mini',
  'scira-seed-2.0-lite': 'bytedance/seed-2.0-lite',
  'scira-mercury-2': 'inception/mercury-2',
} as const;

type SciraModelId = keyof typeof OPENROUTER_MODEL_IDS;

function toOpenRouterModelId(modelId: string) {
  return OPENROUTER_MODEL_IDS[modelId as SciraModelId] ?? OPENROUTER_MODEL_IDS['scira-default'];
}

function shouldExtractReasoning(modelId: string) {
  return modelId.includes('think') || modelId.includes('thinking') || modelId.includes('reasoning');
}

function getOpenRouterLanguageModel(modelId: string) {
  const model = openrouter.chatModel(toOpenRouterModelId(modelId));

  if (!shouldExtractReasoning(modelId)) {
    return model;
  }

  return wrapLanguageModel({
    model,
    middleware: reasoningMiddleware,
  });
}

const languageModels = new Proxy({} as Record<string, ReturnType<typeof getOpenRouterLanguageModel>>, {
  get: (_target, modelId) => (typeof modelId === 'string' ? getOpenRouterLanguageModel(modelId) : undefined),
  has: (_target, modelId) => typeof modelId === 'string',
  getOwnPropertyDescriptor: () => ({
    enumerable: true,
    configurable: true,
  }),
});

export const scira = customProvider({
  languageModels,
});

export type { ModelProvider, ProviderInfo, Model } from './models';
export {
  PROVIDERS,
  models,
  getModelConfig,
  requiresAuthentication,
  requiresProSubscription,
  requiresMaxSubscription,
  isFreeUnlimited,
  hasVisionSupport,
  hasPdfSupport,
  hasReasoningSupport,
  isExperimentalModel,
  getMaxOutputTokens,
  getModelParameters,
  canUseModel,
  shouldBypassRateLimits,
  getAcceptedFileTypes,
  supportsExtremeMode,
  getExtremeModels,
  supportsCanvasMode,
  isModelRestrictedInRegion,
  getFilteredModels,
  authRequiredModels,
  proRequiredModels,
  freeUnlimitedModels,
  getModelProvider,
  getModelProviderInfo,
  getActiveProviders,
  getModelsByProvider,
} from './models';
