import { wrapLanguageModel, customProvider, extractReasoningMiddleware, gateway } from 'ai';

import { createOpenAICompatible } from '@ai-sdk/openai-compatible';
import { groq } from '@ai-sdk/groq';
import { mistral } from '@ai-sdk/mistral';
import { cohere } from '@ai-sdk/cohere';

const middleware = extractReasoningMiddleware({
  tagName: 'think',
});

const middlewareWithStartWithReasoning = extractReasoningMiddleware({
  tagName: 'think',
  startWithReasoning: true,
});

const huggingface = createOpenAICompatible({
  name: 'huggingface',
  baseURL: 'https://router.huggingface.co/v1',
  apiKey: process.env.HF_TOKEN,
});

const novita = createOpenAICompatible({
  name: 'novita',
  baseURL: 'https://api.novita.ai/openai',
  apiKey: process.env.NOVITA_API_KEY,
});

const anannas = createOpenAICompatible({
  name: 'anannas',
  baseURL: 'https://api.anannas.ai/v1',
  apiKey: process.env.ANANNAS_API_KEY,
  headers: {
    'HTTP-Referer': 'https://scira.ai',
    'X-Title': 'Scira AI',
    'Content-Type': 'application/json',
  },
});

const openrouterReferer = (process.env.ALLOWED_ORIGINS?.split(',')[0] ?? 'https://mydatavibes.com').trim();

const openrouter = createOpenAICompatible({
  name: 'openrouter',
  baseURL: 'https://openrouter.ai/api/v1',
  apiKey: process.env.OPENROUTER_API_KEY,
  headers: {
    'HTTP-Referer': openrouterReferer,
    'X-Title': 'Datavibes AI',
  },
});

const baseten = createOpenAICompatible({
  name: 'baseten',
  baseURL: 'https://inference.baseten.co/v1',
  apiKey: process.env.BASETEN_API_KEY,
});


export const scira = customProvider({
  languageModels: {
    'scira-default': openrouter.chatModel('x-ai/grok-4.1-fast'),
    'scira-grok4.1-fast-thinking': openrouter.chatModel('x-ai/grok-4.1-fast'),
    'scira-nano': openrouter.chatModel('meta-llama/llama-3.3-70b-instruct'),
    'scira-name': openrouter.chatModel('google/gemini-2.5-flash-lite-preview-09-2025'),
    'scira-grok-3-mini': openrouter.chatModel('x-ai/grok-3-mini'),
    'scira-grok-3': openrouter.chatModel('x-ai/grok-3'),
    'scira-grok-4': openrouter.chatModel('x-ai/grok-4'),
    'scira-grok-4.20-beta': openrouter.chatModel('x-ai/grok-4.20-beta'),
    'scira-grok-4-fast': openrouter.chatModel('x-ai/grok-4-fast'),
    'scira-grok-4-fast-think': openrouter.chatModel('x-ai/grok-4-fast'),
    'scira-code': openrouter.chatModel('x-ai/grok-code-fast-1'),
    'scira-enhance': openrouter.chatModel('moonshotai/kimi-k2-0905'),
    'scira-follow-up': openrouter.chatModel('x-ai/grok-4.1-fast'),
    'scira-qwen-4b': openrouter.chatModel('qwen/qwen3-4b:free'),
    'scira-qwen-4b-thinking': openrouter.chatModel('qwen/qwen3-4b:free'),
    'scira-gpt-4.1-nano': openrouter.chatModel('openai/gpt-4.1-nano'),
    'scira-gpt-4.1-mini': openrouter.chatModel('openai/gpt-4.1-mini'),
    'scira-gpt-4.1': openrouter.chatModel('openai/gpt-4.1'),
    'scira-gpt-5.1': openrouter.chatModel('openai/gpt-5.1'),
    'scira-gpt-5.1-thinking': openrouter.chatModel('openai/gpt-5.1'),
    'scira-gpt-5.2': openrouter.chatModel('openai/gpt-5.2'),
    'scira-gpt-5.2-thinking': openrouter.chatModel('openai/gpt-5.2'),
    'scira-gpt-5.3-chat': openrouter.chatModel('openai/gpt-5.3-chat'),
    'scira-gpt-5.4': openrouter.chatModel('openai/gpt-5.4'),
    'scira-gpt-5.4-pro': openrouter.chatModel('openai/gpt-5.4-pro'),
    'scira-gpt-5.1-codex': openrouter.chatModel('openai/gpt-5.1-codex'),
    'scira-gpt-5.1-codex-mini': openrouter.chatModel('openai/gpt-5.1-codex-mini'),
    'scira-gpt-5.1-codex-max': openrouter.chatModel('openai/gpt-5.1-codex-max'),
    'scira-gpt5': openrouter.chatModel('openai/gpt-5'),
    'scira-gpt5-medium': openrouter.chatModel('openai/gpt-5'),
    'scira-gpt5-mini': openrouter.chatModel('openai/gpt-5-mini'),
    'scira-gpt5-nano': openrouter.chatModel('openai/gpt-5-nano'),
    'scira-o3': openrouter.chatModel('openai/o3'),
    'scira-o4-mini': openrouter.chatModel('openai/o4-mini'),
    'scira-gpt5-codex': openrouter.chatModel('openai/gpt-5-codex'),
    'scira-qwen-32b': openrouter.chatModel('qwen/qwen3-32b'),
    'scira-qwen-32b-thinking': openrouter.chatModel('qwen/qwen3-32b'),
    'scira-gpt-oss-20': openrouter.chatModel('openai/gpt-oss-20b'),
    'scira-gpt-oss-120': openrouter.chatModel('openai/gpt-oss-120b'),
    'scira-trinity-mini': openrouter.chatModel('arcee-ai/trinity-mini'),
    'scira-kat-coder': openrouter.chatModel('kwaipilot/kat-coder-pro'),
    'scira-deepseek-v3': openrouter.chatModel('deepseek/deepseek-chat-v3-0324'),
    'scira-deepseek-v3.1-terminus': openrouter.chatModel('deepseek/deepseek-v3.1-terminus'),
    'scira-deepseek-chat': openrouter.chatModel('deepseek/deepseek-v3.2'),
    'scira-deepseek-chat-think': openrouter.chatModel('deepseek/deepseek-v3.2'),
    'scira-deepseek-chat-exp': openrouter.chatModel('deepseek/deepseek-v3.2-exp'),
    'scira-deepseek-chat-think-exp': openrouter.chatModel('deepseek/deepseek-v3.2-exp'),
    'scira-v0-10': openrouter.chatModel('openai/gpt-5.1-codex-mini'),
    'scira-v0-15': openrouter.chatModel('openai/gpt-5.1-codex'),
    'scira-deepseek-r1': openrouter.chatModel('deepseek/deepseek-r1'),
    'scira-deepseek-r1-0528': openrouter.chatModel('deepseek/deepseek-r1-0528'),
    'scira-qwen-coder-small': openrouter.chatModel('qwen/qwen3-coder-30b-a3b-instruct'),
    'scira-qwen-coder': openrouter.chatModel('qwen/qwen3-coder'),
    'scira-qwen-coder-plus': openrouter.chatModel('qwen/qwen3-coder-plus'),
    'scira-qwen-30': openrouter.chatModel('qwen/qwen3-30b-a3b-instruct-2507'),
    'scira-qwen-30-think': openrouter.chatModel('qwen/qwen3-30b-a3b-thinking-2507'),
    'scira-qwen-3-vl-30b': openrouter.chatModel('qwen/qwen3-vl-30b-a3b-instruct'),
    'scira-qwen-3-vl-30b-thinking': openrouter.chatModel('qwen/qwen3-vl-30b-a3b-thinking'),
    'scira-qwen-3-next': openrouter.chatModel('qwen/qwen3-next-80b-a3b-instruct'),
    'scira-qwen-3-next-think': openrouter.chatModel('qwen/qwen3-next-80b-a3b-thinking'),
    'scira-qwen-3-max': openrouter.chatModel('qwen/qwen3-max'),
    'scira-qwen-3-max-preview': openrouter.chatModel('qwen/qwen3-max'),
    'scira-qwen-235': openrouter.chatModel('qwen/qwen3-235b-a22b'),
    'scira-qwen-235-think': openrouter.chatModel('qwen/qwen3-235b-a22b-thinking-2507'),
    'scira-qwen-3-vl': openrouter.chatModel('qwen/qwen3-vl-235b-a22b-instruct'),
    'scira-qwen-3-vl-thinking': openrouter.chatModel('qwen/qwen3-vl-235b-a22b-thinking'),
    'scira-glm-air': openrouter.chatModel('z-ai/glm-4.5-air'),
    'scira-glm': openrouter.chatModel('z-ai/glm-4.5'),
    'scira-glm-4.6': openrouter.chatModel('z-ai/glm-4.6'),
    'scira-glm-4.6v-flash': openrouter.chatModel('z-ai/glm-4.7-flash'),
    'scira-glm-4.6v': openrouter.chatModel('z-ai/glm-4.6v'),
    'scira-glm-4.7': openrouter.chatModel('z-ai/glm-4.7'),
    'scira-glm-5': openrouter.chatModel('z-ai/glm-5'),
    'scira-minimax': openrouter.chatModel('minimax/minimax-m1'),
    'scira-minimax-m2': openrouter.chatModel('minimax/minimax-m2'),
    'scira-minimax-m2.1': openrouter.chatModel('minimax/minimax-m2.1'),
    'scira-minimax-m2.5': openrouter.chatModel('minimax/minimax-m2.5'),
    'scira-minimax-m2.1-lightning': openrouter.chatModel('minimax/minimax-m2.5'),
    'scira-cmd-a': openrouter.chatModel('cohere/command-a'),
    'scira-cmd-a-think': openrouter.chatModel('cohere/command-a'),
    'scira-kimi-k2-v2': openrouter.chatModel('moonshotai/kimi-k2-0905'),
    'scira-kimi-k2-v2-thinking': openrouter.chatModel('moonshotai/kimi-k2-thinking'),
    'scira-kimi-k2.5': openrouter.chatModel('moonshotai/kimi-k2.5'),
    'scira-haiku': openrouter.chatModel('anthropic/claude-3.5-haiku'),
    'scira-ministral-3b': openrouter.chatModel('mistralai/ministral-3b-2512'),
    'scira-ministral-8b': openrouter.chatModel('mistralai/ministral-8b-2512'),
    'scira-ministral-14b': openrouter.chatModel('mistralai/ministral-14b-2512'),
    'scira-mistral-large': openrouter.chatModel('mistralai/mistral-large-2512'),
    'scira-mistral-medium': openrouter.chatModel('mistralai/mistral-medium-3.1'),
    'scira-magistral-small': openrouter.chatModel('mistralai/mistral-small-3.2-24b-instruct'),
    'scira-magistral-medium': openrouter.chatModel('mistralai/mistral-medium-3.1'),
    'scira-devstral': openrouter.chatModel('mistralai/devstral-2512'),
    'scira-devstral-small': openrouter.chatModel('mistralai/devstral-small'),
    'scira-google-lite': openrouter.chatModel('google/gemini-2.5-flash-lite'),
    'scira-google': openrouter.chatModel('google/gemini-2.5-flash'),
    'scira-google-think': openrouter.chatModel('google/gemini-2.5-flash'),
    'scira-google-pro': openrouter.chatModel('google/gemini-2.5-pro-preview'),
    'scira-google-pro-think': openrouter.chatModel('google/gemini-2.5-pro-preview'),
    'scira-gemini-3-flash': openrouter.chatModel('google/gemini-3-flash-preview'),
    'scira-gemini-3-flash-think': openrouter.chatModel('google/gemini-3-flash-preview'),
    'scira-gemini-3-pro': openrouter.chatModel('google/gemini-3-pro-preview'),
    'scira-gemini-3.1-flash-lite': openrouter.chatModel('google/gemini-3.1-flash-lite-preview'),
    'scira-gemini-3.1-pro': openrouter.chatModel('google/gemini-3.1-pro-preview-customtools'),
    'scira-anthropic-small': openrouter.chatModel('anthropic/claude-haiku-4.5'),
    'scira-anthropic': openrouter.chatModel('anthropic/claude-sonnet-4.5'),
    'scira-anthropic-think': openrouter.chatModel('anthropic/claude-sonnet-4.5'),
    'scira-anthropic-4.6': openrouter.chatModel('anthropic/claude-sonnet-4.6'),
    'scira-mimo-v2-flash': openrouter.chatModel('xiaomi/mimo-v2-flash'),
    'scira-anthropic-opus': openrouter.chatModel('anthropic/claude-opus-4.5'),
    'scira-anthropic-opus-think': openrouter.chatModel('anthropic/claude-opus-4.5'),
    'scira-anthropic-opus-4.6': openrouter.chatModel('anthropic/claude-opus-4.6'),
    'scira-nova-2-lite': openrouter.chatModel('amazon/nova-2-lite-v1'),
  },
});

interface ModelParameters {
  temperature?: number;
  topP?: number;
  topK?: number;
  minP?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
  maxOutputTokens?: number;
}

interface Model {
  value: string;
  label: string;
  description: string;
  vision: boolean;
  reasoning: boolean;
  experimental: boolean;
  category: string;
  pdf: boolean;
  pro: boolean;
  requiresAuth: boolean;
  freeUnlimited: boolean;
  maxOutputTokens: number;
  extreme?: boolean;
  fast?: boolean;
  isNew?: boolean;
  parameters?: ModelParameters;
}

export const models: Model[] = [
  // Models (xAI)
  {
    value: 'scira-grok-3-mini',
    label: 'Grok 3 Mini',
    description: "xAI's recent smallest LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 16000,
  },
  {
    value: 'scira-grok-3',
    label: 'Grok 3',
    description: "xAI's recent smartest LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
  },
  {
    value: 'scira-grok-4',
    label: 'Grok 4',
    description: "xAI's most intelligent LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
  },
  {
    value: 'scira-grok-4.20-beta',
    label: 'Grok 4.20 Beta',
    description: "xAI's newest experimental flagship LLM",
    vision: true,
    reasoning: true,
    experimental: true,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-default',
    label: 'Grok 4.1 Fast',
    description: "xAI's greatest and fastest multimodel LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: true,
  },
  {
    value: 'scira-grok4.1-fast-thinking',
    label: 'Grok 4.1 Fast Thinking',
    description: "xAI's greatest and fastest multimodel reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: true,
  },
  {
    value: 'scira-grok-4-fast',
    label: 'Grok 4 Fast',
    description: "xAI's previous fastest multimodel LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: true,
  },
  {
    value: 'scira-grok-4-fast-think',
    label: 'Grok 4 Fast Thinking',
    description: "xAI's previous fastest multimodel reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: true,
    parameters: {
      maxOutputTokens: 30000,
    },
  },
  {
    value: 'scira-code',
    label: 'Grok Code',
    description: "xAI's advanced coding LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
  },
  {
    value: 'scira-qwen-32b',
    label: 'Qwen 3 32B',
    description: "Alibaba's base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 40960,
    fast: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-32b-thinking',
    label: 'Qwen 3 32B Thinking',
    description: "Alibaba's base reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 40960,
    fast: true,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-4b',
    label: 'Qwen 3 4B',
    description: "Alibaba's small base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    maxOutputTokens: 16000,
    freeUnlimited: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-4b-thinking',
    label: 'Qwen 3 4B Thinking',
    description: "Alibaba's small base LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    maxOutputTokens: 16000,
    freeUnlimited: false,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-gpt-oss-20',
    label: 'GPT OSS 20B',
    description: "OpenAI's small OSS LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
  },
  {
    value: 'scira-gpt5-nano',
    label: 'GPT 5 Nano',
    description: "OpenAI's smallest flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: true,
  },
  {
    value: 'scira-google-lite',
    label: 'Gemini 2.5 Flash Lite',
    description: "Google's advanced small LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    extreme: true,
    isNew: true,
  },
  {
    value: 'scira-ministral-3b',
    label: 'Ministral 3 3B',
    description: "Mistral's mini-model 3B multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-ministral-8b',
    label: 'Ministral 3 8B',
    description: "Mistral's mini-model 8B multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-devstral',
    label: 'Devstral 2',
    description: "Mistral's coding-focused LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-devstral-small',
    label: 'Devstral Small 2',
    description: "Mistral's small coding-focused LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-ministral-14b',
    label: 'Ministral 3 14B',
    description: "Mistral's mini-model 14B multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-mistral-large',
    label: 'Mistral Large 3',
    description: "Mistral's latest and greatest large multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-mistral-medium',
    label: 'Mistral Medium',
    description: "Mistral's medium multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-magistral-small',
    label: 'Magistral Small',
    description: "Mistral's small reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-magistral-medium',
    label: 'Magistral Medium',
    description: "Mistral's medium reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-trinity-mini',
    label: 'Trinity Mini',
    description: "Arcee's small reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    parameters: {
      temperature: 0.15,
      topK: 50,
      topP: 0.75,
      minP: 0.06,
    },
  },
  {
    value: 'scira-gpt-oss-120',
    label: 'GPT OSS 120B',
    description: "OpenAI's advanced OSS LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
  },
  {
    value: 'scira-gpt-4.1-nano',
    label: 'GPT 4.1 Nano',
    description: "OpenAI's smallest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: true,
  },
  {
    value: 'scira-gpt-4.1-mini',
    label: 'GPT 4.1 Mini',
    description: "OpenAI's small LLM",
    vision: true,
    reasoning: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    extreme: true,
    experimental: false,
  },
  {
    value: 'scira-gpt-4.1',
    label: 'GPT 4.1',
    description: "OpenAI's LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.1',
    label: 'GPT 5.1 Instant',
    description: "OpenAI's fast and smart LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.1-thinking',
    label: 'GPT 5.1 Thinking',
    description: "OpenAI's recent and smart reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.2',
    label: 'GPT 5.2 Instant',
    description: "OpenAI's latest and greatest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.2-thinking',
    label: 'GPT 5.2 Thinking',
    description: "OpenAI's latest and greatest reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.3-chat',
    label: 'GPT 5.3 Chat',
    description: "OpenAI's newest chat-tuned GPT model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.4',
    label: 'GPT 5.4',
    description: "OpenAI's newest flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.4-pro',
    label: 'GPT 5.4 Pro',
    description: "OpenAI's highest-end GPT 5.4 model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt5-mini',
    label: 'GPT 5 Mini',
    description: "OpenAI's small flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt5',
    label: 'GPT 5',
    description: "OpenAI's flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-o4-mini',
    label: 'o4 mini',
    description: "OpenAI's recent mini reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-o3',
    label: 'o3',
    description: "OpenAI's advanced LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt5-medium',
    label: 'GPT 5 Medium',
    description: "OpenAI's latest flagship reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.1-codex',
    label: 'GPT 5.1 Codex',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.1-codex-mini',
    label: 'GPT 5.1 Codex Mini',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt-5.1-codex-max',
    label: 'GPT 5.1 Codex Max',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-gpt5-codex',
    label: 'GPT 5 Codex',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
  },
  {
    value: 'scira-cmd-a',
    label: 'Command A',
    description: "Cohere's advanced command LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-cmd-a-think',
    label: 'Command A Thinking',
    description: "Cohere's advanced command LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-kat-coder',
    label: 'KAT-Coder-Pro V1',
    description: "Kwaipilot's advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-deepseek-v3',
    label: 'DeepSeek v3',
    description: "DeepSeek's previous advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-deepseek-v3.1-terminus',
    label: 'DeepSeek v3.1 Terminus',
    description: "DeepSeek's advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-deepseek-chat',
    label: 'DeepSeek v3.2',
    description: "DeepSeek's advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
    },
  },
  {
    value: 'scira-deepseek-chat-think',
    label: 'DeepSeek v3.2 Thinking',
    description: "DeepSeek's advanced chat LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-deepseek-chat-exp',
    label: 'DeepSeek v3.2 Exp',
    description: "DeepSeek's advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-deepseek-chat-think-exp',
    label: 'DeepSeek v3.2 Exp Thinking',
    description: "DeepSeek's advanced chat LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-deepseek-r1',
    label: 'DeepSeek R1',
    description: "DeepSeek's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-deepseek-r1-0528',
    label: 'DeepSeek R1 0528',
    description: "DeepSeek's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-qwen-coder-small',
    label: 'Qwen 3 Coder 30B A3B Instruct',
    description: "Alibaba's advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    isNew: true,
  },
  {
    value: 'scira-qwen-coder',
    label: 'Qwen 3 Coder',
    description: "Alibaba's advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: true,
  },
  {
    value: 'scira-qwen-coder-plus',
    label: 'Qwen 3 Coder Plus',
    description: "Alibaba's extremely advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: false,
  },
  {
    value: 'scira-qwen-3-vl-30b',
    label: 'Qwen 3 VL 30B',
    description: "Alibaba's advanced vision LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-3-vl-30b-thinking',
    label: 'Qwen 3 VL 30B Thinking',
    description: "Alibaba's advanced vision LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    isNew: true,
  },
  {
    value: 'scira-qwen-3-next',
    label: 'Qwen 3 Next 80B A3B Instruct',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    fast: true,
    isNew: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-3-next-think',
    label: 'Qwen 3 Next 80B A3B Thinking',
    description: "Qwen's advanced thinking LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    isNew: true,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-3-max',
    label: 'Qwen 3 Max',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-qwen-3-max-preview',
    label: 'Qwen 3 Max Preview',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-qwen-235',
    label: 'Qwen 3 235B A22B',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-235-think',
    label: 'Qwen 3 235B A22B Thinking',
    description: "Qwen's advanced thinking LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
  },
  {
    value: 'scira-qwen-3-vl',
    label: 'Qwen 3 VL 235B A22B Instruct',
    description: "Qwen's advanced vision LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
    isNew: true,
  },
  {
    value: 'scira-qwen-3-vl-thinking',
    label: 'Qwen 3 VL 235B A22B Thinking',
    description: "Qwen's advanced vision LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
    isNew: true,
  },
  {
    value: 'scira-kimi-k2-v2',
    label: 'Kimi K2 Latest',
    description: "MoonShot AI's advanced base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    parameters: {
      temperature: 0.6,
    },
  },
  {
    value: 'scira-kimi-k2-v2-thinking',
    label: 'Kimi K2 Thinking',
    description: "MoonShot AI's advanced base LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    parameters: {
      temperature: 1,
    },
    isNew: true,
  },
  {
    value: 'scira-kimi-k2.5',
    label: 'Kimi K2.5',
    description: "MoonShot AI's newest flagship reasoning model",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    parameters: {
      temperature: 0.8,
    },
    isNew: true,
  },
  // sherlock experimental models

  {
    value: 'scira-minimax',
    label: 'Minimax M1 80K',
    description: "Minimax's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    parameters: {
      temperature: 0.6,
    },
  },
  {
    value: 'scira-minimax-m2',
    label: 'Minimax M2',
    description: "Minimax's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    value: 'scira-minimax-m2.1',
    label: 'Minimax M2.1',
    description: "Minimax's latest advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    value: 'scira-minimax-m2.5',
    label: 'Minimax M2.5',
    description: "Minimax's newest advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    value: 'scira-minimax-m2.1-lightning',
    label: 'Minimax M2.1 Lightning',
    description: "Minimax's fast advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    fast: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
  },
  {
    value: 'scira-glm-4.6',
    label: 'GLM 4.6',
    description: "Zhipu AI's advanced reasoning LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    fast: true,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
    },
  },
  {
    value: 'scira-glm-4.6v-flash',
    label: 'GLM 4.6V Flash',
    description: "Zhipu AI's fast vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    fast: true,
    parameters: {
      temperature: 0.8,
      topP: 0.6,
      topK: 2,
      frequencyPenalty: 1.1,
    },
  },
  {
    value: 'scira-glm-4.6v',
    label: 'GLM 4.6V',
    description: "Zhipu AI's advanced vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    parameters: {
      temperature: 0.8,
      topP: 0.6,
      topK: 2,
      frequencyPenalty: 1.1,
    },
  },
  {
    value: 'scira-glm-4.7',
    label: 'GLM 4.7',
    description: "Zhipu AI's latest advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    fast: true,
    parameters: {
      temperature: 1,
      topP: 0.95,
    },
  },
  {
    value: 'scira-glm-5',
    label: 'GLM 5',
    description: "Zhipu AI's newest flagship reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    fast: true,
    parameters: {
      temperature: 1,
      topP: 0.95,
    },
  },
  {
    value: 'scira-glm-air',
    label: 'GLM 4.5 Air',
    description: "Zhipu AI's efficient base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
    },
  },
  {
    value: 'scira-glm',
    label: 'GLM 4.5',
    description: "Zhipu AI's previous advanced LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 13000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
    },
  },
  {
    value: 'scira-google',
    label: 'Gemini 2.5 Flash',
    description: "Google's advanced small LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-google-think',
    label: 'Gemini 2.5 Flash Thinking',
    description: "Google's advanced small LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-google-pro',
    label: 'Gemini 2.5 Pro',
    description: "Google's advanced LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-google-pro-think',
    label: 'Gemini 2.5 Pro Thinking',
    description: "Google's advanced LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-gemini-3-flash',
    label: 'Gemini 3 Flash',
    description: "Google's latest small SOTA LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-gemini-3-flash-think',
    label: 'Gemini 3 Flash Thinking',
    description: "Google's latest small SOTA LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-gemini-3-pro',
    label: 'Gemini 3 Pro',
    description: "Google's latest SOTA LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-gemini-3.1-flash-lite',
    label: 'Gemini 3.1 Flash Lite',
    description: "Google's newest lightweight multimodal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    description: "Google's newest flagship multimodal LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
  },
  {
    value: 'scira-anthropic-small',
    label: 'Claude Haiku 4.5',
    description: "Anthropic's fast and efficient LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
  },
  {
    value: 'scira-anthropic',
    label: 'Claude Sonnet 4.5',
    description: "Anthropic's latest and greatest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
  },
  {
    value: 'scira-anthropic-think',
    label: 'Claude Sonnet 4.5 Thinking',
    description: "Anthropic's latest and greatest LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
  },
  {
    value: 'scira-anthropic-4.6',
    label: 'Claude Sonnet 4.6',
    description: "Anthropic's newest flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
  },
  {
    value: 'scira-anthropic-opus',
    label: 'Claude 4.5 Opus',
    description: "Anthropic's latest and greatest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
  },
  {
    value: 'scira-anthropic-opus-4.6',
    label: 'Claude Opus 4.6',
    description: "Anthropic's newest highest-end LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
  },
  {
    value: 'scira-anthropic-opus-think',
    label: 'Claude 4.5 Opus Thinking',
    description: "Anthropic's latest and greatest LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
  },
  {
    value: 'scira-mimo-v2-flash',
    label: 'Mimo V2 Flash',
    description: "Xiaomi's fast Mimo V2 Flash model via OpenRouter (thinking disabled)",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-nova-2-lite',
    label: 'Nova 2 Lite',
    description: "Amazon's latest and smallest LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-v0-10',
    label: 'Vercel v0 1.0',
    description: "Vercel's v0 1.0 model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
  {
    value: 'scira-v0-15',
    label: 'Vercel v0 1.5',
    description: "Vercel's v0 1.5 model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
  },
];

// Helper functions for model access checks
export function getModelConfig(modelValue: string) {
  return models.find((model) => model.value === modelValue);
}

export function requiresAuthentication(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.requiresAuth || false;
}

export function requiresProSubscription(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.pro || false;
}

export function isFreeUnlimited(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.freeUnlimited || false;
}

export function hasVisionSupport(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.vision || false;
}

export function hasPdfSupport(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.pdf || false;
}

export function hasReasoningSupport(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.reasoning || false;
}

export function isExperimentalModel(modelValue: string): boolean {
  const model = getModelConfig(modelValue);
  return model?.experimental || false;
}

export function getMaxOutputTokens(modelValue: string): number {
  const model = getModelConfig(modelValue);
  return model?.maxOutputTokens || 8000;
}

export function getModelParameters(modelValue: string): ModelParameters {
  const model = getModelConfig(modelValue);
  return model?.parameters || {};
}

// Access control helper
export function canUseModel(modelValue: string, user: any, isProUser: boolean): { canUse: boolean; reason?: string } {
  const model = getModelConfig(modelValue);

  if (!model) {
    return { canUse: false, reason: 'Model not found' };
  }

  // Check if model requires authentication
  if (model.requiresAuth && !user) {
    return { canUse: false, reason: 'authentication_required' };
  }

  // Check if model requires Pro subscription
  if (model.pro && !isProUser) {
    return { canUse: false, reason: 'pro_subscription_required' };
  }

  return { canUse: true };
}

// Helper to check if user should bypass rate limits
export function shouldBypassRateLimits(modelValue: string, user: any): boolean {
  const model = getModelConfig(modelValue);
  return Boolean(user && model?.freeUnlimited);
}

// Get acceptable file types for a model
export function getAcceptedFileTypes(modelValue: string, isProUser: boolean): string {
  const model = getModelConfig(modelValue);
  if (model?.pdf && isProUser) {
    return 'image/*,.pdf';
  }
  return 'image/*';
}

// Check if a model supports extreme mode
export function supportsExtremeMode(modelValue: string): boolean {
  // Extreme mode restrictions removed: allow all models in extreme mode
  return true;
}

// Get models that support extreme mode
export function getExtremeModels(): Model[] {
  // With restrictions removed, all models are considered extreme-capable
  return models;
}

// Restricted regions for OpenAI and Anthropic models
const RESTRICTED_REGIONS = ['CN', 'KP', 'RU']; // China, North Korea, Russia

// Models that should be filtered in restricted regions
const OPENAI_MODELS = [
  'scira-gpt-4.1',
  'scira-gpt-4.1-mini',
  'scira-gpt-4.1-nano',
  'scira-gpt5',
  'scira-gpt5-mini',
  'scira-gpt5-nano',
  'scira-gpt5-medium',
  'scira-gpt5-codex',
  'scira-gpt-5.1',
  'scira-gpt-5.1-codex',
  'scira-gpt-5.1-codex-mini',
  'scira-gpt-5.1-codex-max',
  'scira-gpt-5.1-thinking',
  'scira-gpt-5.2',
  'scira-gpt-5.2-thinking',
  'scira-gpt-5.3-chat',
  'scira-gpt-5.4',
  'scira-gpt-5.4-pro',
  'scira-o3',
  'scira-o4-mini',
];

const ANTHROPIC_MODELS = [
  'scira-haiku',
  'scira-anthropic-small',
  'scira-anthropic',
  'scira-anthropic-4.6',
  'scira-anthropic-think',
  'scira-anthropic-opus',
  'scira-anthropic-opus-4.6',
  'scira-anthropic-opus-think',
];

// Check if a model should be filtered based on region
export function isModelRestrictedInRegion(modelValue: string, countryCode?: string): boolean {
  if (!countryCode) return false;

  const isRestricted = RESTRICTED_REGIONS.includes(countryCode.toUpperCase());
  if (!isRestricted) return false;

  const isOpenAI = OPENAI_MODELS.includes(modelValue);
  const isAnthropic = ANTHROPIC_MODELS.includes(modelValue);

  return isOpenAI || isAnthropic;
}

// Filter models based on user's region
export function getFilteredModels(countryCode?: string): Model[] {
  if (!countryCode || !RESTRICTED_REGIONS.includes(countryCode.toUpperCase())) {
    return models;
  }

  return models.filter((model) => !isModelRestrictedInRegion(model.value, countryCode));
}

// Legacy arrays for backward compatibility (deprecated - use helper functions instead)
export const authRequiredModels = models.filter((m) => m.requiresAuth).map((m) => m.value);
export const proRequiredModels = models.filter((m) => m.pro).map((m) => m.value);
export const freeUnlimitedModels = models.filter((m) => m.freeUnlimited).map((m) => m.value);
